### PR TITLE
Update some more references to old S3 environment variables

### PR DESCRIPTION
**Pull request by dobesv**
I noticed the old S3_* environment variables were still referenced in a few places, this cleans those up to use the standard names

### CODE REVIEW

**Comment by dlehmhus** [comment]
Hey @dobesv, I think one issue here is, that those env vars are [reserved](https://vercel.com/docs/concepts/projects/environment-variables#reserved-environment-variables) for vercel! One solution would be, updating the aws-sdk config manually like [this](https://vercel.com/support/articles/how-can-i-use-aws-sdk-environment-variables-on-vercel).

**Comment by dobesv** [comment]
Ah interesting, I guess for Vercel this might still need to have an alternate set of environment variables it can use instead of the AWS_* ones.  Probably more than I will take on for now but I'll file an issue at least to track it.

**Comment by fox1t** [comment]
Now that I recall this is the reason we used those names in the first place. We need to fix this ASAP.

**Comment by dobesv** [comment]
I guess I should have kept the backwards compatibility in there after all!  Anyway it's just a few lines of code.

**Pull request closed without merging**
